---
- name: Install packages
  package:
    name: "{{ certbot_package }}"
    state: present

- name: Get installed certificates
  command: certbot certificates
  changed_when: no
  register: certbot_certificates_command

- name: Set installed certificates
  set_fact:
    certbot_installed_certificates: >
      {{ certbot_certificates_command.stdout |
         regex_findall('Certificate Name: (.+)') }}

- name: Add deploy hook option when defined
  set_fact:
    certbot_command: >
      {{ certbot_command + [ '--deploy-hook', certbot_deploy_hook | quote ] }}
  when: certbot_deploy_hook is defined

- name: Install certificates
  command: >
    {{ certbot_command | join(' ') }}
    --email "{{ certbot_email }}"
    --cert-name "{{ item.key }}"
    --domains "{{ item.value | join(',') }}"
  when: >
    certbot_force_renewal or
    not item.key in certbot_installed_certificates
  loop: "{{ certbot_certificates | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
